# Generated by Django 2.2.16 on 2020-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
