# Generated by Django 2.2.16 on 2020-10-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='nav',
            name='updated_time',
        ),
    ]
